/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel.database.management;
import java.awt.Color;
import java.awt.Container;
import java.sql.*;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Amoli Shah
 */
public class LoginPage extends javax.swing.JFrame {
    private String Username;
    private String Password;

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
   this.getContentPane().setBackground(Color.CYAN);
   PassWordTxt.setText("");
   PassWordTxt.setEchoChar('*');
      
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        UserNameLbl = new javax.swing.JLabel();
        PassWordLbl = new javax.swing.JLabel();
        UserNameTxt = new javax.swing.JTextField();
        LogInBtn = new javax.swing.JButton();
        SignUpBtn = new javax.swing.JButton();
        SignInBtn = new javax.swing.JButton();
        PassWordTxt = new javax.swing.JPasswordField();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN PAGE");
        setBackground(new java.awt.Color(255, 51, 102));

        jLabel1.setBackground(new java.awt.Color(255, 255, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("WELCOME TO HOTEL RAMADA");
        jLabel1.setToolTipText("");

        UserNameLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UserNameLbl.setForeground(new java.awt.Color(0, 51, 204));
        UserNameLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserNameLbl.setText("USERNAME");

        PassWordLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PassWordLbl.setForeground(new java.awt.Color(0, 51, 204));
        PassWordLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PassWordLbl.setText("PASSWORD");

        UserNameTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UserNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameTxtActionPerformed(evt);
            }
        });

        LogInBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LogInBtn.setForeground(new java.awt.Color(0, 51, 204));
        LogInBtn.setText("LOG IN");
        LogInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInBtnActionPerformed(evt);
            }
        });

        SignUpBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SignUpBtn.setForeground(new java.awt.Color(0, 51, 204));
        SignUpBtn.setText("NEW USER");
        SignUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpBtnActionPerformed(evt);
            }
        });

        SignInBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SignInBtn.setForeground(new java.awt.Color(0, 51, 204));
        SignInBtn.setText("Sign In");
        SignInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignInBtnActionPerformed(evt);
            }
        });

        PassWordTxt.setText("jPasswordField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UserNameLbl)
                    .addComponent(PassWordLbl)
                    .addComponent(LogInBtn))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SignUpBtn)
                    .addComponent(UserNameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(SignInBtn))
                    .addComponent(PassWordTxt))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LogInBtn)
                    .addComponent(SignUpBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(UserNameLbl)
                    .addComponent(UserNameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PassWordLbl)
                    .addComponent(PassWordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(SignInBtn)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameTxtActionPerformed

    private void SignUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpBtnActionPerformed
       SignUpPage sp = new SignUpPage();
       sp.setVisible(true);
    }//GEN-LAST:event_SignUpBtnActionPerformed

    private void LogInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInBtnActionPerformed
        UserNameTxt.requestFocus();
        Username = UserNameTxt.getText();
        Password = Arrays.toString(PassWordTxt.getPassword());
    }//GEN-LAST:event_LogInBtnActionPerformed

    private void SignInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignInBtnActionPerformed
        try {
            // TODO add your handling code here:
            Connection myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/Example1", "root" , "Pranav Mistry");
            
            // 2. Create a statement
            Statement myStmt = myConn.createStatement();
           
            // 3. Execute SQL query
             ResultSet myRs = myStmt.executeQuery("SELECT * FROM credentials");
            // 4. Process the result set
          /*  while (myRs.next()) {
             System.out.println(myRs.getString("UserName") + ", " + myRs.getString("Password") + "," + myRs.getString("EmailID"));
            }*/
            Username = UserNameTxt.getText();
             Password = Arrays.toString(PassWordTxt.getPassword());
             if("".equals(Username) || "".equals(Password))
                 JOptionPane.showMessageDialog(null,"Please Enter Details","ERROR",JOptionPane.ERROR_MESSAGE);
             else{
            while (myRs.next()) {
                if(myRs.getString("UserName").equals(Username)){
                   if(myRs.getString("Password").equals(Password)){
                        JOptionPane.showMessageDialog(null,"Welcome " + Username + "!");
                        WelcomePage wp = new WelcomePage();
                        wp.setVisible(true);
                    }
                   else
                        JOptionPane.showMessageDialog(null,"The Username and Password you entered don't match.","ERROR",JOptionPane.ERROR_MESSAGE);
                }}}
           // myStmt.executeUpdate("DELETE FROM Credentials");
        } catch (SQLException ex) {
            Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SignInBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
        LoginPage p = new LoginPage();
        p.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogInBtn;
    private javax.swing.JLabel PassWordLbl;
    private javax.swing.JPasswordField PassWordTxt;
    private javax.swing.JButton SignInBtn;
    private javax.swing.JButton SignUpBtn;
    private javax.swing.JLabel UserNameLbl;
    private javax.swing.JTextField UserNameTxt;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
